-- ============================================================================
-- NFL STATISTICS DATABASE SCHEMA
-- ============================================================================

CREATE TABLE nfl_season (
    season_id INT AUTO_INCREMENT PRIMARY KEY,
    year INT NOT NULL UNIQUE,
    start_date DATE,
    end_date DATE
);

CREATE TABLE nfl_team (
    team_id INT AUTO_INCREMENT PRIMARY KEY,
    team_name VARCHAR(255) NOT NULL,
    abrv VARCHAR(3) NOT NULL,
    alt_abrv VARCHAR(3),
    conference ENUM('AFC', 'NFC') NOT NULL,
    division ENUM('North', 'South', 'East', 'West') NOT NULL,
    indoor_stadium TINYINT(1) NOT NULL,
    warm_climate TINYINT(1) NOT NULL,
    stadium_address VARCHAR(255),
    stadium_latitude DECIMAL(8, 6),
    stadium_latitude_direction ENUM('N', 'S'),
    stadium_longitude DECIMAL(9, 6),
    stadium_longitude_direction ENUM('E', 'W')
);

CREATE TABLE nfl_standings (
    nfl_standings_id INT AUTO_INCREMENT PRIMARY KEY,
    team_id INT,
    season_id INT,
    week_id INT,
    win INT,
    loss INT,
    win_loss_pct DECIMAL(7,4),
    pt_for INT,
    pt_against INT,
    pt_diff INT,
    margin_of_victory DECIMAL(7,4),
    strength_of_schedule DECIMAL(7,4),
    simple_rating_system DECIMAL(7,4),
    off_srs DECIMAL(7,4),
    def_srs DECIMAL(7,4),
    UNIQUE KEY uk_tm_season (team_id, season_id, week_id),
    FOREIGN KEY (team_id) REFERENCES nfl_team(team_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
);

CREATE TABLE nfl_week (
    week_id INT PRIMARY KEY AUTO_INCREMENT,
    season_id INT,
    week_num VARCHAR(7),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id),
    UNIQUE KEY uk_season_week (season_id, week_num)
);

CREATE TABLE nfl_gm_quarter (
    nfl_quarter_id INT PRIMARY KEY AUTO_INCREMENT,
    quarter INT NOT NULL UNIQUE
);

CREATE TABLE nfl_game (
    game_id INT PRIMARY KEY AUTO_INCREMENT,
    week_id INT,
    season_id INT,
    home_team_id INT,
    away_team_id INT,
    home_team_score INT,
    away_team_score INT,
    game_date DATE,
    game_time TIME,
    game_result ENUM('home_win', 'away_win', 'tie'),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id),
    FOREIGN KEY (home_team_id) REFERENCES nfl_team(team_id),
    FOREIGN KEY (away_team_id) REFERENCES nfl_team(team_id),
    UNIQUE KEY (season_id, week_id, home_team_id, away_team_id)
);

CREATE TABLE nfl_game_info (
    game_info_id INT PRIMARY KEY AUTO_INCREMENT,
    game_id INT,
    week_id INT,
    season_id INT,
    won_toss_tm_id INT,
    is_deferred TINYINT,
    stadium_roof VARCHAR(20),
    duration TIME,
    attendance INT,
    kickoff_temp INT,
    kickoff_humidity FLOAT(7,4),
    windspeed INT,
    vegas_line_tm_id INT,
    vegas_line FLOAT,
    over_under_line FLOAT,
    over_under_result VARCHAR(10),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (game_id) REFERENCES nfl_game(game_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id),
    FOREIGN KEY (won_toss_tm_id) REFERENCES nfl_team(team_id),
    FOREIGN KEY (vegas_line_tm_id) REFERENCES nfl_team(team_id),
    UNIQUE KEY (game_id) 
);

CREATE TABLE plyr_master (
    plyr_guid VARCHAR(64) PRIMARY KEY,
    plyr_name VARCHAR(255) NOT NULL,
    plyr_birthday DATE,
    plyr_college VARCHAR(255),
    plyr_draft_tm VARCHAR(255),
    plyr_draft_rd TINYINT UNSIGNED,
    plyr_draft_pick SMALLINT UNSIGNED,
    plyr_draft_yr SMALLINT UNSIGNED,
    primary_pos VARCHAR(10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_plyr_name (plyr_name),
    INDEX idx_plyr_draft_yr (plyr_draft_yr),
    INDEX idx_primary_pos (primary_pos)
);

CREATE TABLE plyr (
    plyr_id INT AUTO_INCREMENT PRIMARY KEY,
    plyr_guid VARCHAR(64),
    team_id INT,
    season_id INT,
    plyr_name VARCHAR(255) NOT NULL,
    plyr_age TINYINT UNSIGNED,
    plyr_pos VARCHAR(10),
    plyr_alt_pos VARCHAR(10),
    plyr_gm_played TINYINT UNSIGNED,
    plyr_gm_started TINYINT UNSIGNED,
    plyr_weight SMALLINT UNSIGNED,
    plyr_height SMALLINT UNSIGNED,
    plyr_yrs_played TINYINT UNSIGNED,
    plyr_birthday DATE NOT NULL,
    plyr_avg_value TINYINT,
    plyr_draft_tm VARCHAR(255) NOT NULL,
    is_on_ir TINYINT UNSIGNED,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (plyr_guid) REFERENCES plyr_master(plyr_guid),
    FOREIGN KEY (team_id) REFERENCES nfl_team(team_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id),
    INDEX idx_plyr_name (plyr_name),
    INDEX idx_team_season (team_id, season_id),
    INDEX idx_plyr_pos (plyr_pos),
    UNIQUE KEY uk_player_season_pos_exp (plyr_name, season_id, plyr_birthday, plyr_draft_tm)
);

-- CREATE TABLE multi_tm_plyr (
--     multi_tm_plyr_id INT AUTO_INCREMENT PRIMARY KEY,
--     plyr_id INT,
--     plyr_guid VARCHAR(64),
--     season_id INT,
--     current_tm_id INT,
--     former_tm_id INT,
--     first_tm_id INT,
--     current_tm_week_id INT,
--     former_tm_lst_wk_id INT,
--     first_tm_lst_wk_id INT,
--     second_tm_week_id INT,
--     plyr_name VARCHAR(255) NOT NULL,
--     plyr_pos VARCHAR(10),
--     plyr_age INT,
--     plyr_gm_played INT,
--     plyr_gm_started INT,
--     plyr_weight INT,
--     plyr_height INT,
--     plyr_yrs_played INT,
--     plyr_college VARCHAR(255),
--     plyr_birthday DATE,
--     plyr_avg_value DECIMAL(5,2),
--     plyr_draft_tm VARCHAR(255),
--     plyr_draft_rd INT,
--     plyr_draft_pick INT,
--     plyr_draft_yr INT,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
--     FOREIGN KEY (plyr_guid) REFERENCES plyr_master(plyr_guid),
--     FOREIGN KEY (plyr_id) REFERENCES plyr(plyr_id),
--     FOREIGN KEY (season_id) REFERENCES nfl_season(season_id),
--     FOREIGN KEY (current_tm_id) REFERENCES nfl_team(team_id),
--     FOREIGN KEY (former_tm_id) REFERENCES nfl_team(team_id),
--     FOREIGN KEY (first_tm_id) REFERENCES nfl_team(team_id),
--     FOREIGN KEY (current_tm_week_id) REFERENCES nfl_week(week_id),
--     FOREIGN KEY (former_tm_lst_wk_id) REFERENCES nfl_week(week_id),
--     FOREIGN KEY (second_tm_week_id) REFERENCES nfl_week(week_id),
--     FOREIGN KEY (first_tm_lst_wk_id) REFERENCES nfl_week(week_id),
--     UNIQUE KEY uk_plyr_season_pos_exp (plyr_name, season_id, plyr_birthday, plyr_draft_tm)
-- );

CREATE TABLE multi_tm_plyr (
    multi_tm_plyr_id INT AUTO_INCREMENT PRIMARY KEY,
    season_id INT,
    plyr_id INT,
    plyr_guid VARCHAR(64),
    plyr_name VARCHAR(255) NOT NULL,
    tm_1_id INT, -- First team in the season
    tm_2_id INT, -- Second team in the season
    tm_3_id INT, -- Third team in the season
    first_tm_week_start_id INT, -- Week the player started with the first team
    first_tm_week_end_id INT, -- Week the player ended with the first team
    second_tm_week_start_id INT, -- Week the player started with the second team
    second_tm_week_end_id INT, -- Week the player ended with the second team
    third_tm_week_start_id INT, -- Week the player started with the third team
    third_tm_week_end_id INT, -- Week the player ended with the third team
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (plyr_guid) REFERENCES plyr_master(plyr_guid),
    FOREIGN KEY (plyr_id) REFERENCES plyr(plyr_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id),
    FOREIGN KEY (tm_1_id) REFERENCES nfl_team(team_id),
    FOREIGN KEY (tm_2_id) REFERENCES nfl_team(team_id),
    FOREIGN KEY (tm_3_id) REFERENCES nfl_team(team_id),
    FOREIGN KEY (tm_1_week_start_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (tm_1_week_end_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (tm_2_week_start_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (tm_2_week_end_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (tm_3_week_start_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (tm_3_week_end_id) REFERENCES nfl_week(week_id),
    UNIQUE KEY uk_plyr_season_pos_exp (season_id, plyr_guid)
);

    CREATE TABLE injury_report (
        injury_report_id INT AUTO_INCREMENT PRIMARY KEY,
        season_id INT,
        plyr_id INT,
        plyr_name VARCHAR(255) NOT NULL,
        team_id INT,
        game_id INT,
        week_id INT,
        was_inactive TINYINT,
        wed_practice_status VARCHAR(20),
        thurs_practice_status VARCHAR(20),
        fri_practice_status VARCHAR(20),
        sat_practice_status VARCHAR(20),
        game_status VARCHAR(20),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        FOREIGN KEY (season_id) REFERENCES nfl_season(season_id),
        FOREIGN KEY (plyr_id) REFERENCES plyr(plyr_id),
        FOREIGN KEY (game_id) REFERENCES nfl_game(game_id),
        FOREIGN KEY (team_id) REFERENCES nfl_team(team_id),
        FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
        UNIQUE KEY uk_plyr_season_game (plyr_id, game_id)
    );


-- CREATE TABLE injured_reserve (
--     injury_report_id INT AUTO_INCREMENT PRIMARY KEY,
--     season_id INT,
--     plyr_id INT,
--     plyr_name VARCHAR(255) NOT NULL,
--     team_id INT,
--     week_id INT,
--     is_on_ir TINYINT,
--     FOREIGN KEY (season_id) REFERENCES nfl_season(season_id),
--     FOREIGN KEY (plyr_id) REFERENCES plyr(plyr_id),
--     FOREIGN KEY (team_id) REFERENCES nfl_team(team_id),
--     FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
--     UNIQUE KEY uk_plyr_season_game (plyr_id, season_id)
-- );

CREATE TABLE nfl_gm_pbp (
    game_pbp_id INT PRIMARY KEY AUTO_INCREMENT,
    game_id INT,
    week_id INT,
    season_id INT,
    team_id INT,
    gm_pbp_qtr_id INT,
    gm_pbp_time VARCHAR(10),  -- Added time field
    gm_pbp_dwn INT,
    gm_pbn_yds_to_go INT,
    gm_pbp_location_side VARCHAR(3),
    gm_pbp_location_yd_line INT,
    gm_pbp_home_tm_score INT,
    gm_pbp_away_tm_score INT,
    gm_pbp_detail VARCHAR(500),  -- Increased size for longer play descriptions
    gm_pbp_ebp FLOAT,
    gm_pbp_epa FLOAT,
    FOREIGN KEY (gm_pbp_qtr_id) REFERENCES nfl_gm_quarter(nfl_quarter_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (game_id) REFERENCES nfl_game(game_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id),
    FOREIGN KEY (team_id) REFERENCES nfl_team(team_id),
    UNIQUE KEY unique_play (game_id, gm_pbp_qtr_id, gm_pbp_time)
);

CREATE TABLE nfl_gm_weather (
    gm_weather_id INT AUTO_INCREMENT PRIMARY KEY,
    seaason_id INT,
    game_id INT,
    week_id INT,
    kickoff_temperature DECIMAL(7,4),
    kickoff_humidity DECIMAL(7,4),
    kickoff_feels_like_temperature DECIMAL(7,4),
    kickoff_precipitation DECIMAL(5,4),
    kickoff_rain DECIMAL(5,4),
    kickoff_snowfall DECIMAL(5,4),
    kickoff_snow_depth DECIMAL(5,4),
    kickoff_wind_speed DECIMAL(6,4),
    kickoff_wind_direction DECIMAL(7,4),
    kickoff_wind_gusts DECIMAL(6,4),
    first_half_temperature DECIMAL(7,4),
    first_half_humidity DECIMAL(7,4),
    first_half_feels_like_temperature DECIMAL(7,4),
    first_half_precipitation DECIMAL(5,4),
    first_half_rain DECIMAL(5,4),
    first_half_snowfall DECIMAL(5,4),
    first_half_snow_depth DECIMAL(5,4),
    first_half_wind_speed DECIMAL(6,4),
    first_half_wind_direction DECIMAL(7,4),
    first_half_wind_gusts DECIMAL(6,4),
    second_half_temperature DECIMAL(7,4),
    second_half_humidity DECIMAL(7,4),
    second_half_feels_like_temperature DECIMAL(7,4),
    second_half_precipitation DECIMAL(5,4),
    second_half_rain DECIMAL(5,4),
    second_half_snowfall DECIMAL(5,4),
    second_half_snow_depth DECIMAL(5,4),
    second_half_wind_speed DECIMAL(6,4),
    second_half_wind_direction DECIMAL(7,4),
    second_half_wind_gusts DECIMAL(6,4),
    end_of_game_temperature DECIMAL(7,4),
    end_of_game_humidity DECIMAL(7,4),
    end_of_game_feels_like_temperature DECIMAL(7,4),
    end_of_game_precipitation DECIMAL(5,4),
    end_of_game_rain DECIMAL(5,4),
    end_of_game_snowfall DECIMAL(5,4),
    end_of_game_snow_depth DECIMAL(5,4),
    end_of_game_wind_speed DECIMAL(6,4),
    end_of_game_wind_direction DECIMAL(7,4),
    end_of_game_wind_gusts DECIMAL(6,4),
    UNIQUE KEY (game_id, week_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id),
    FOREIGN KEY (game_id) REFERENCES nfl_game(game_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id)
);

CREATE TABLE plyr_def (
    plyr_def_id INT AUTO_INCREMENT PRIMARY KEY,
    plyr_id INT,
    season_id INT,
    week_id INT,
    plyr_def_int INT,
    plyr_def_int_yds INT,
    plyr_def_int_td INT,
    plyr_def_int_lng INT,
    plyr_pass_def INT,
    plyr_def_force_fmbl INT,
    plyr_def_fmbl_rec INT,
    plyr_def_fmbl_rec_yds INT,
    plyr_def_fmbl_rec_td INT,
    plyr_def_solo_tkl INT,
    plyr_def_tkl_assist INT,
    plyr_def_tfl INT,
    plyr_def_qb_hit INT,
    plyr_def_sfty INT,
    plyr_def_tgt INT,
    plyr_def_cmp INT,
    plyr_def_cmp_pct DECIMAL(7,4),
    plyr_def_pass_yds INT,
    plyr_def_pass_yds_cmp DECIMAL(7,4),
    plyr_def_pass_yds_tgt DECIMAL(7,4),
    plyr_def_pass_td INT,
    plyr_def_pass_rtg DECIMAL(7,4),
    plyr_def_adot DECIMAL(7,4),
    plyr_def_ay INT,
    plyr_def_yac INT,
    plyr_def_bltz INT,
    plyr_def_hrry INT,
    plyr_def_qbkd INT,
    plyr_def_sk DECIMAL(7,4),
    plyr_def_prss INT,
    plyr_def_comb_tkl INT,
    plyr_def_mtkl INT,
    plyr_def_mtkl_pct DECIMAL(7,4),
    UNIQUE KEY uk_plyr_season (plyr_id, season_id, week_id),
    FOREIGN KEY (plyr_id) REFERENCES plyr(plyr_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id)
);

CREATE TABLE plyr_gm_def (
    plyr_gm_def_id INT PRIMARY KEY AUTO_INCREMENT,
    plyr_id INT,
    week_id INT,
    game_id INT,
    season_id INT,
    team_id INT,
    plyr_gm_def_int INT,
    plyr_gm_def_int_yds INT,
    plyr_gm_def_int_td INT,
    plyr_gm_def_int_lng INT,
    plyr_gm_pass_def INT,
    plyr_gm_def_comb_tkl INT,
    plyr_gm_def_solo_tkl INT,
    plyr_gm_def_tkl_assist INT,
    plyr_gm_def_tfl INT,
    plyr_gm_def_qb_hit INT,
    plyr_gm_def_fmble_rec INT,
    plyr_gm_def_fmbl_ret_yds INT,
    plyr_gm_def_fmbl_td INT,
    plyr_gm_def_force_fmbl INT,
    plyr_gm_def_tgt INT,
    plyr_gm_def_cmp INT,
    plyr_gm_def_cmp_pct FLOAT(5,4),
    plyr_gm_def_pass_yds INT,
    plyr_gm_def_pass_yds_cmp FLOAT(7,4),
    plyr_gm_def_pass_yds_tgt FLOAT(7,4),
    plyr_gm_def_pass_td INT,
    plyr_gm_def_pass_rtg FLOAT(7,4),
    plyr_gm_def_adot FLOAT(7,4),
    plyr_gm_def_ay INT,
    plyr_gm_def_yac INT,
    plyr_gm_def_bltz INT,
    plyr_gm_def_hrry INT,
    plyr_gm_def_qbkd INT,
    plyr_gm_def_sk INT,
    plyr_gm_def_prss INT,
    plyr_gm_def_mtkl INT,
    plyr_gm_def_mtkl_pct FLOAT(5,4),
    FOREIGN KEY (plyr_id) REFERENCES plyr(plyr_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (game_id) REFERENCES nfl_game(game_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id),
    FOREIGN KEY (team_id) REFERENCES nfl_team(team_id),
    UNIQUE KEY uk_player_game (plyr_id, game_id)
);

CREATE TABLE plyr_gm_fmbl (
    plyr_gm_fmbl_id INT PRIMARY KEY AUTO_INCREMENT,
    plyr_id INT,
    week_id INT,
    game_id INT,
    season_id INT,
    team_id INT,
    plyr_gm_fmbl INT,
    plyr_gm_fl INT,
    FOREIGN KEY (plyr_id) REFERENCES plyr(plyr_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (game_id) REFERENCES nfl_game(game_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id),
    FOREIGN KEY (team_id) REFERENCES nfl_team(team_id),
    UNIQUE KEY uk_player_game (plyr_id, game_id)
);

CREATE TABLE plyr_pass (
    plyr_pass_id INT AUTO_INCREMENT PRIMARY KEY,
    plyr_id INT,
    season_id INT,
    week_id INT,
    qb_win INT,
    qb_loss INT,
    qb_tie INT,
    plyr_pass_cmp INT,
    plyr_pass_att INT,
    plyr_pass_cmp_pct DECIMAL(6,4),  -- Updated 2025-10-11: Precision standardization (5,4 -> 6,4)
    plyr_pass_yds INT,
    plyr_pass_td INT,
    plyr_pass_td_pct DECIMAL(7,4),
    plyr_pass_int INT,
    plyr_pass_int_pct DECIMAL(6,4),  -- Updated 2025-10-11: Precision standardization (5,4 -> 6,4)
    plyr_pass_first_dwn INT,
    plyr_pass_succ_rt DECIMAL(7,4),
    plyr_pass_lng INT,
    plyr_pass_yds_att DECIMAL(7,4),
    plyr_pass_adj_yds_att DECIMAL(7,4),
    plyr_pass_yds_cmp DECIMAL(7,4),
    plyr_pass_yds_gm DECIMAL(7,4),
    plyr_pass_rtg DECIMAL(7,4),
    plyr_qbr DECIMAL(7,4),
    plyr_pass_sk INT,
    plyr_pass_sk_yds INT,
    plyr_pass_sk_pct DECIMAL(6,4),  -- Updated 2025-10-11: Precision standardization (5,4 -> 6,4)
    plyr_pass_net_yds_att DECIMAL(7,4),
    plyr_pass_adj_net_yds_att DECIMAL(7,4),
    plyr_fqc INT,
    plyr_gwd INT,
    plyr_pass_adv_yds INT,
    plyr_pass_iay INT,
    plyr_pass_iay_att DECIMAL(7,4),
    plyr_pass_cmp_ay INT,
    plyr_pass_cay_cmp DECIMAL(7,4),
    plyr_pass_cay_att DECIMAL(7,4),
    plyr_pass_yac INT,
    plyr_pass_yac_cmp DECIMAL(7,4),
    plyr_rpo_play INT,
    plyr_rpo_yds INT,
    plyr_rpo_pass_att INT,
    plyr_rpo_pass_yds INT,
    plyr_rpo_rush_att INT,
    plyr_rpo_rush_yds INT,
    plyr_pa_att INT,
    plyr_pa_yds INT,
    plyr_pass_pkt_time TIME(3),
    plyr_pass_bltz INT,
    plyr_pass_hrry INT,
    plyr_pass_hit INT,
    plyr_pass_prss INT,
    plyr_pass_prss_pct DECIMAL(6,4),  -- Updated 2025-10-11: Precision standardization (4,3 -> 6,4)
    plyr_pass_scrmbl INT,
    plyr_pass_yds_scrmbl DECIMAL(4,1),
    UNIQUE KEY uk_plyr_season (plyr_id, week_id, season_id),
    FOREIGN KEY (plyr_id) REFERENCES plyr(plyr_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id)
);

CREATE TABLE plyr_gm_pass (
    adv_plyr_gm_pass_id INT PRIMARY KEY AUTO_INCREMENT,
    plyr_id INT,
    week_id INT,
    game_id INT,
    season_id INT,
    team_id INT,
    plyr_gm_pass_cmp INT,
    plyr_gm_pass_att INT,
    plyr_gm_pass_yds INT,
    plyr_gm_pass_td INT,
    plyr_gm_pass_int INT,
    plyr_gm_pass_sk INT,
    plyr_gm_pass_sk_yds INT,
    plyr_gm_pass_lng INT,
    plyr_gm_pass_rtg FLOAT(7,4),
    plyr_gm_pass_first_dwn INT,
    plyr_gm_pass_first_dwn_pct DECIMAL(6,4),  -- Updated 2025-10-11: Precision standardization (FLOAT 5,4 -> DECIMAL 6,4)
    plyr_gm_pass_iay INT,
    plyr_gm_pass_iay_att FLOAT(7,4),
    plyr_gm_pass_cay INT,
    plyr_gm_pass_cay_cmp FLOAT(7,4),
    plyr_gm_pass_cay_att FLOAT(7,4),
    plyr_gm_pass_yac INT,
    plyr_gm_pass_yac_cmp FLOAT(7,4),
    plyr_gm_pass_drp INT,
    plyr_gm_pass_drp_pct DECIMAL(6,4),  -- Updated 2025-10-11: Precision standardization (FLOAT 5,4 -> DECIMAL 6,4)
    plyr_gm_pass_off_tgt INT,
    plyr_gm_pass_off_tgt_pct DECIMAL(6,4),  -- Updated 2025-10-11: Precision standardization (FLOAT 5,4 -> DECIMAL 6,4)
    plyr_gm_pass_bltz INT,
    plyr_gm_pass_hrry INT,
    plyr_gm_pass_hit INT,
    plyr_gm_pass_prss INT,
    plyr_gm_pass_prss_pct DECIMAL(6,4),  -- Updated 2025-10-11: Precision standardization (FLOAT 5,4 -> DECIMAL 6,4)
    plyr_gm_pass_scrmbl_tgt INT,
    plyr_gm_pass_yds_scrmbl FLOAT(7,4),
    plyr_gm_pass_cmp_pct DECIMAL(6,4),  -- Updated 2025-10-11: Precision standardization (DECIMAL 7,4 -> 6,4)
    plyr_gm_pass_td_pct DECIMAL(6,4),  -- Updated 2025-10-11: Precision standardization (DECIMAL 7,4 -> 6,4)
    plyr_gm_pass_int_pct DECIMAL(6,4),  -- Updated 2025-10-11: Precision standardization (DECIMAL 7,4 -> 6,4)
    plyr_gm_pass_yds_att DECIMAL(7,4),
    plyr_gm_pass_adj_yds_att DECIMAL(7,4),
    plyr_gm_pass_yds_cmp DECIMAL(7,4),
    plyr_gm_pass_sk_pct DECIMAL(6,4),  -- Updated 2025-10-11: Precision standardization (DECIMAL 7,4 -> 6,4)
    plyr_gm_pass_net_yds_att DECIMAL(7,4),
    plyr_gm_pass_adj_net_yds_att DECIMAL(7,4),
    FOREIGN KEY (plyr_id) REFERENCES plyr(plyr_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (game_id) REFERENCES nfl_game(game_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id),
    FOREIGN KEY (team_id) REFERENCES nfl_team(team_id),
    UNIQUE KEY uk_player_game (plyr_id, game_id)
);

CREATE TABLE plyr_rec (
    plyr_rec_id INT AUTO_INCREMENT PRIMARY KEY,
    plyr_id INT,
    season_id INT,
    week_id INT,
    plyr_rec_tgt INT,
    plyr_rec INT,
    plyr_rec_catch_pct DECIMAL(6,4),
    plyr_rec_yds INT,
    plyr_rec_yds_rec DECIMAL(7,4),
    plyr_rec_td INT,
    plyr_rec_first_dwn INT,
    plyr_rec_succ_rt DECIMAL(7,4),
    plyr_rec_lng INT,
    plyr_rec_yds_tgt DECIMAL(7,4),
    plyr_rec_gm DECIMAL(7,4),
    plyr_rec_ypg DECIMAL(7,4),
    plyr_rec_fmbl INT,
    plyr_rec_aybc INT,
    plyr_rec_aybc_rec DECIMAL(7,4),
    plyr_rec_yac INT,
    plyr_rec_yac_rec DECIMAL(7,4),
    plyr_rec_adot DECIMAL(7,4),
    plyr_rec_brkn_tkl INT,
    plyr_rec_brkn_tkl_rec DECIMAL(7,4),
    plyr_rec_drp INT,
    plyr_rec_drp_pct DECIMAL(5,4),
    plyr_rec_int INT,
    plyr_rec_pass_rtg DECIMAL(7,4),
    UNIQUE KEY uk_plyr_season (plyr_id, season_id, week_id),
    FOREIGN KEY (plyr_id) REFERENCES plyr(plyr_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
);

CREATE TABLE plyr_gm_rec (
    adv_plyr_gm_rec_id INT PRIMARY KEY AUTO_INCREMENT,
    plyr_id INT,
    week_id INT,
    game_id INT,
    season_id INT,
    team_id INT,
    plyr_gm_rec_tgt INT,
    plyr_gm_rec INT,
    plyr_gm_rec_yds INT,
    plyr_gm_rec_td INT,
    plyr_gm_rec_lng INT,
    plyr_gm_fmbl INT,
    plyr_gm_fl INT,
    plyr_gm_rec_first_dwn INT,
    plyr_gm_rec_aybc INT,
    plyr_gm_rec_aybc_route FLOAT(7,4),
    plyr_gm_rec_yac INT,
    plyr_gm_rec_yac_route FLOAT(7,4),
    plyr_gm_rec_adot FLOAT(7,4),
    plyr_gm_rec_brkn_tkl INT,
    plyr_gm_rec_brkn_tkl_rec FLOAT(7,4),
    plyr_gm_rec_drp INT,
    plyr_gm_rec_drp_pct FLOAT(7,4),
    plyr_gm_rec_int INT,
    plyr_gm_rec_pass_rtg FLOAT(7,4),
    plyr_rec_catch_pct DECIMAL(6,4),
    plyr_rec_yds_tgt DECIMAL(7,4),
    FOREIGN KEY (plyr_id) REFERENCES plyr(plyr_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (game_id) REFERENCES nfl_game(game_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id),
    FOREIGN KEY (team_id) REFERENCES nfl_team(team_id),
    UNIQUE KEY uk_player_game (plyr_id, game_id)
);

CREATE TABLE plyr_rush (
    plyr_rush_id INT AUTO_INCREMENT PRIMARY KEY,
    plyr_id INT,
    season_id INT,
    week_id INT,
    plyr_rush_att INT,
    plyr_rush_yds INT,
    plyr_rush_td INT,
    plyr_rush_first_dwn INT,
    plyr_rush_succ_rt DECIMAL(7,4),
    plyr_rush_lng INT,
    plyr_rush_yds_att DECIMAL(7,4),
    plyr_rush_yds_gm DECIMAL(7,4),
    plyr_rush_fmbl INT,
    plyr_rush_ybc INT,
    plyr_rush_ybc_att DECIMAL(7,4),
    plyr_rush_yac INT,
    plyr_rush_yac_att DECIMAL(7,4),
    plyr_rush_brkn_tkl INT,
    plyr_rush_brkn_tkl_att DECIMAL(7,4),
    UNIQUE KEY uk_plyr_season (plyr_id, season_id, week_id),
    FOREIGN KEY (plyr_id) REFERENCES plyr(plyr_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id)
);

CREATE TABLE plyr_gm_rush (
    adv_plyr_gm_rush_id INT PRIMARY KEY AUTO_INCREMENT,
    plyr_id INT,
    week_id INT,
    game_id INT,
    season_id INT,
    team_id INT,
    plyr_gm_rush_att INT,
    plyr_gm_rush_yds INT,
    plyr_gm_rush_yds_att DECIMAL(7,4),
    plyr_gm_rush_td INT,
    plyr_gm_rush_lng INT,
    plyr_gm_rush_first_dwn INT,
    plyr_gm_rush_ybc INT,
    plyr_gm_rush_ybc_att FLOAT(7,4),
    plyr_gm_rush_yac INT,
    plyr_gm_rush_yac_att FLOAT(7,4),
    plyr_gm_rush_brkn_tkl INT,
    plyr_gm_rush_brkn_tkl_att FLOAT(7,4),
    FOREIGN KEY (plyr_id) REFERENCES plyr(plyr_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (game_id) REFERENCES nfl_game(game_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id),
    FOREIGN KEY (team_id) REFERENCES nfl_team(team_id),
    UNIQUE KEY uk_player_game (plyr_id, game_id)
);

CREATE TABLE plyr_gm_snap_ct (
    plyr_gm_snap_count_id INT PRIMARY KEY AUTO_INCREMENT,
    plyr_id INT,
    week_id INT,
    game_id INT,
    season_id INT,
    team_id INT,
    plyr_gm_off_snap_ct INT,
    plyr_gm_off_snap_ct_pct FLOAT(5,4),
    plyr_gm_def_snap_ct INT,
    plyr_gm_def_snap_ct_pct FLOAT(5,4),
    plyr_gm_st_snap_ct INT,
    plyr_gm_st_snap_ct_pct FLOAT(5,4),
    FOREIGN KEY (plyr_id) REFERENCES plyr(plyr_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (game_id) REFERENCES nfl_game(game_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id),
    FOREIGN KEY (team_id) REFERENCES nfl_team(team_id),
    UNIQUE KEY uk_player_game (plyr_id, game_id)
);

CREATE TABLE plyr_gm_starters (
    plyr_gm_starters_id INT PRIMARY KEY AUTO_INCREMENT,
    plyr_id INT,
    team_id INT,
    week_id INT,
    game_id INT,
    season_id INT,  
    plyr_gm_pos VARCHAR(5),
    FOREIGN KEY (plyr_id) REFERENCES plyr(plyr_id),
    FOREIGN KEY (team_id) REFERENCES team(team_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (game_id) REFERENCES nfl_game(game_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id),
    UNIQUE KEY uk_player_game (plyr_id, game_id)
);

CREATE TABLE plyr_rz_pass (
    plyr_rz_pass_id INT AUTO_INCREMENT PRIMARY KEY,
    plyr_id INT,
    season_id INT,
    week_id INT,
    plyr_pass_rz_cmp INT,
    plyr_pass_rz_att INT,
    plyr_pass_rz_cmp_pct DECIMAL(5,4),
    plyr_pass_rz_yds INT,
    plyr_pass_rz_td INT,
    plyr_pass_rz_int INT,
    plyr_pass_tz_cmp INT,
    plyr_pass_tz_att INT,
    plyr_pass_tz_cmp_pct DECIMAL(5,4),
    plyr_pass_tz_yds INT,
    plyr_pass_tz_td INT,
    plyr_pass_tz_int INT,
    UNIQUE KEY uk_plyr_season (plyr_id, season_id, week_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (plyr_id) REFERENCES plyr(plyr_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id)
);

CREATE TABLE plyr_rz_rec (
    plyr_rz_rec_id INT AUTO_INCREMENT PRIMARY KEY,
    plyr_id INT,
    season_id INT,
    week_id INT,
    plyr_rec_rz_tgt INT,
    plyr_rec_rz INT,
    plyr_rec_rz_catch_pct DECIMAL(5,4),
    plyr_rec_rz_yds INT,
    plyr_rec_rz_td INT,
    plyr_rec_rz_tgt_pct DECIMAL(5,4),
    plyr_rec_tz_tgt INT,
    plyr_rec_tz INT,
    plyr_rec_tz_catch_pct DECIMAL(5,4),
    plyr_rec_tz_yds INT,
    plyr_rec_tz_td INT,
    plyr_rec_tz_tgt_pct DECIMAL(5,4),
    UNIQUE KEY uk_plyr_season (plyr_id, season_id, week_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (plyr_id) REFERENCES plyr(plyr_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id)
);

CREATE TABLE plyr_rz_rush (
    plyr_rz_rush_id INT AUTO_INCREMENT PRIMARY KEY,
    plyr_id INT,
    season_id INT,
    week_id INT,
    plyr_rush_rz_att INT,
    plyr_rush_rz_yds INT,
    plyr_rush_rz_td INT,
    plyr_rush_rz_usage DECIMAL(7,4),
    plyr_rush_tz_att INT,
    plyr_rush_tz_yds INT,
    plyr_rush_tz_td INT,
    plyr_rush_tz_usage DECIMAL(7,4),   
    plyr_rush_fz_att INT,
    plyr_rush_fz_yds INT,
    plyr_rush_fz_td INT,
    plyr_rush_fz_usage DECIMAL(7,4),
    UNIQUE KEY uk_plyr_season (plyr_id, season_id, week_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (plyr_id) REFERENCES plyr(plyr_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id)
);

CREATE TABLE plyr_scoring (
    plyr_scoring_id INT AUTO_INCREMENT PRIMARY KEY,
    plyr_id INT,
    season_id INT,
    week_id INT,
    plyr_pr_td INT,
    plyr_kr_td INT,
    plyr_oth_td INT,
    plyr_tot_td INT,
    plyr_two_pt_conv INT,
    plyr_two_pt_conv_att INT,
    plyr_def_two_pt_conv INT,
    plyr_ex_pt_md INT,
    plyr_ex_pt_att INT,
    plyr_fg_md INT,
    plyr_fg_att INT,
    plyr_tot_pt INT,
    plyr_tot_pt_gm DECIMAL(7,4),
    UNIQUE KEY uk_plyr_season (plyr_id, season_id, week_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (plyr_id) REFERENCES plyr(plyr_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id)
);

CREATE TABLE tm_def (
    tm_def_id INT AUTO_INCREMENT PRIMARY KEY,
    team_id INT,
    season_id INT,
    week_id INT,
    tm_def_pts_allwd INT,
    tm_def_yds INT,
    tm_def_ply INT,
    tm_def_ypp DECIMAL(7,4),
    tm_def_tkawy INT,
    tm_def_first_dwn INT,
    tm_def_pass_first_dwn INT,
    tm_def_rush_first_dwn INT,
    tm_def_penalty INT,
    tm_def_penalty_yds INT,
    tm_def_penalty_first_dwn INT,
    tm_def_score_pct DECIMAL(5,4),
    tm_def_to_pct DECIMAL(5,4),
    tm_def_exp DECIMAL(7,4),
    tm_def_bltz INT,
    tm_def_bltz_pct DECIMAL(5,4),
    tm_def_hrry INT,
    tm_def_hrry_pct DECIMAL(5,4),
    tm_def_qbkd INT,
    tm_def_qbkd_pct DECIMAL(5,4),
    tm_def_sk INT,
    tm_def_prss INT,
    tm_def_prss_pct DECIMAL(5,4),
    tm_def_missed_tkl INT,
    UNIQUE KEY uk_tm_season (team_id, season_id, week_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (team_id) REFERENCES nfl_team(team_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id)
);


CREATE TABLE tm_pass (
    tm_pass_id INT AUTO_INCREMENT PRIMARY KEY,
    team_id INT,
    season_id INT,
    week_id INT,
    tm_pass_cmp INT,
    tm_pass_att INT,
    tm_pass_cmp_pct DECIMAL(5,4),
    tm_pass_yds INT,
    tm_pass_td INT,
    tm_pass_td_pct DECIMAL(5,4),
    tm_pass_int INT,
    tm_pass_int_pct DECIMAL(5,4),
    tm_pass_lng INT,
    tm_pass_yds_att DECIMAL(7,4),
    tm_pass_adj_yds_att DECIMAL(7,4),
    tm_pass_yds_cmp DECIMAL(7,4),
    tm_pass_yds_gm DECIMAL(7,4),
    tm_pass_rtg DECIMAL(7,4),
    tm_pass_sk INT,
    tm_pass_sack_yds INT,
    tm_pass_sk_pct DECIMAL(5,4),
    tm_pass_net_yds_att DECIMAL(7,4),
    tm_pass_adj_net_yds_att DECIMAL(7,4),
    tm_fqc INT,
    tm_gwd INT,
    tm_pass_exp DECIMAL(7,4),
    tm_pass_bttd INT,
    tm_pass_thrwawy INT,
    tm_pass_spk INT,
    tm_pass_drp INT,
    tm_pass_drp_pct DECIMAL(5,4),
    tm_pass_off_tgt INT,
    tm_pass_off_tgt_pct DECIMAL(5,4),
    tm_pass_on_tgt INT,
    tm_pass_on_tgt_pct DECIMAL(5,4),
    tm_pass_adv_yds INT,
    tm_pass_iay INT,
    tm_pass_iay_att DECIMAL(7,4),
    tm_pass_cay INT,
    tm_pass_cay_cmp DECIMAL(7,4),
    tm_pass_cay_att DECIMAL(7,4),
    tm_pass_yac INT,
    tm_pass_yac_cmp DECIMAL(7,4),
    tm_rpo_play INT,
    tm_rpo_yds INT,
    tm_rpo_pass_att INT,
    tm_rpo_pass_yds INT,
    tm_rpo_rush_att INT,
    tm_rpo_rush_yds INT,
    tm_pa_att INT,
    tm_pa_yds INT,
    tm_pass_pkt_time TIME(3),
    tm_pass_bltz INT,
    tm_pass_hrry INT,
    tm_pass_hit INT,
    tm_pass_prss INT,
    tm_pass_prss_pct DECIMAL(5,4),
    tm_pass_scrmbl INT,
    tm_pass_yds_scrmbl DECIMAL(7,4),
    UNIQUE KEY uk_tm_season (team_id, season_id, week_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (team_id) REFERENCES nfl_team(team_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id)
);

CREATE TABLE tm_rec (
    tm_rec_id INT AUTO_INCREMENT PRIMARY KEY,
    team_id INT,
    season_id INT,
    week_id INT,
    tm_rec_tgt INT,
    tm_rec INT,
    tm_rec_yds INT,
    tm_rec_td INT,
    tm_rec_first_dwn INT,
    tm_rec_ybc INT,
    tm_rec_ybc_rec DECIMAL(7,4),
    tm_rec_yac INT,
    tm_rec_yac_rec DECIMAL(7,4),
    tm_rec_adot DECIMAL(7,4),
    tm_rec_brkn_tkl INT,
    tm_rec_brkn_tkl_rec DECIMAL(7,4),
    tm_rec_drp INT,
    tm_rec_drp_pct DECIMAL(5,4),
    UNIQUE KEY uk_tm_season (team_id, season_id, week_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (team_id) REFERENCES nfl_team(team_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id)
);


CREATE TABLE tm_rush (
    tm_rush_id INT AUTO_INCREMENT PRIMARY KEY,
    team_id INT,
    season_id INT,
    week_id INT,
    tm_rush_att INT,
    tm_rush_yds INT,
    tm_rush_td INT,
    tm_rush_lng INT,
    tm_rush_yds_att DECIMAL(7,4),
    tm_rush_yds_gm DECIMAL(7,4),
    tm_rush_fmbl INT,
    tm_rush_exp DECIMAL(7,4),
    tm_rush_first_dwn INT,
    tm_rush_ybc INT,
    tm_rush_ybc_att DECIMAL(7,4),
    tm_rush_yac INT,
    tm_rush_yac_att DECIMAL(7,4),
    tm_rush_brkn_tkl INT,
    tm_rush_att_brkn_tkl DECIMAL(7,4),
    UNIQUE KEY uk_tm_season (team_id, season_id, week_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (team_id) REFERENCES nfl_team(team_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id)
);

CREATE TABLE tm_conv (
    tm_conv_id INT AUTO_INCREMENT PRIMARY KEY,
    team_id INT,
    season_id INT,
    week_id INT,
    tm_third_dwn_att INT,
    tm_third_dwn_conv INT,
    tm_third_dwn_conv_pct DECIMAL(5,4),
    tm_fourth_dwn_att INT,
    tm_fourth_dwn_conv INT,
    tm_fourth_dwn_conv_pct DECIMAL(5,4),
    tm_rz_att INT,
    tm_rz_td INT,
    tm_rz_conv_pct DECIMAL(5,4),
    UNIQUE KEY uk_tm_season (team_id, season_id, week_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (team_id) REFERENCES nfl_team(team_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id)
);

CREATE TABLE tm_def_conv (
    tm_def_conv_id INT AUTO_INCREMENT PRIMARY KEY,
    team_id INT,
    season_id INT,
    week_id INT,
    tm_def_third_dwn_att INT,
    tm_def_third_dwn_conv INT,
    tm_def_third_dwn_conv_pct DECIMAL(5,4),
    tm_def_fourth_dwn_att INT,
    tm_def_fourth_dwn_conv INT,
    tm_def_fourth_dwn_conv_pct DECIMAL(5,4),
    tm_def_rz_att INT,
    tm_def_rz_td INT,
    tm_def_rz_conv_pct DECIMAL(5,4),
    UNIQUE KEY uk_tm_season (team_id, season_id, week_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (team_id) REFERENCES nfl_team(team_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id)
);

CREATE TABLE tm_def_dr_against_avg (
    tm_def_dr_against_avg_id INT AUTO_INCREMENT PRIMARY KEY,
    team_id INT,
    season_id INT,
    week_id INT,
    tm_def_dr INT,
    tm_def_opp_avg_play_dr DECIMAL(7,4),
    tm_def_opp_net_yds_dr DECIMAL(7,4),
    tm_def_avg_field_pos DECIMAL(7,4),
    tm_def_avg_dr_time TIME,
    tm_def_avg_pt_dr DECIMAL(7,4),
    UNIQUE KEY uk_tm_season (team_id, season_id, week_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (team_id) REFERENCES nfl_team(team_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id)
);

CREATE TABLE tm_def_pass (
    tm_def_pass_id INT AUTO_INCREMENT PRIMARY KEY,
    team_id INT,
    season_id INT,
    week_id INT,
    tm_def_pass_cmp INT,
    tm_def_pass_att INT,
    tm_def_pass_cmp_pct DECIMAL(5,4),  -- Updated 2025-10-11: Precision standardization (7,4 -> 5,4)
    tm_def_pass_yds INT,
    tm_def_pass_td INT,
    tm_def_pass_td_pct DECIMAL(5,4),
    tm_def_int INT,
    tm_def_pass_def INT,
    tm_def_int_pct DECIMAL(5,4),
    tm_def_pass_yds_att DECIMAL(7,4),
    tm_def_pass_yds_att_adj DECIMAL(7,4),
    tm_def_pass_ypc DECIMAL(7,4),
    tm_def_pass_ypg DECIMAL(7,4),
    tm_def_pass_rtg DECIMAL(7,4),
    tm_def_sk INT,
    tm_def_sk_yds INT,
    tm_def_qb_hit INT,
    tm_def_tfl INT,
    tm_def_sk_pct DECIMAL(5,4),
    tm_def_pass_net_yds_att DECIMAL(7,4),
    tm_def_pass_net_yds_att_adj DECIMAL(7,4),
    tm_def_pass_exp DECIMAL(7,4),
    UNIQUE KEY uk_tm_season (team_id, season_id, week_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (team_id) REFERENCES nfl_team(team_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id)
);

CREATE TABLE tm_def_rush (
    tm_def_rush_id INT AUTO_INCREMENT PRIMARY KEY,
    team_id INT,
    season_id INT,
    week_id INT,
    tm_def_rush_att INT,
    tm_def_rush_yds INT,
    tm_def_rush_td INT,
    tm_def_rush_yds_att DECIMAL(7,4),
    tm_def_rush_yds_gm DECIMAL(7,4),
    tm_def_rush_exp DECIMAL(7,4),
    UNIQUE KEY uk_tm_season (team_id, season_id, week_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (team_id) REFERENCES nfl_team(team_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id)
);

CREATE TABLE tm_gm_drive (
    tm_gm_drive_id INT PRIMARY KEY AUTO_INCREMENT,
    team_id INT,
    week_id INT,
    game_id INT,
    season_id INT,
    tm_gm_dr_num INT,
    tm_gm_dr_qtr_id INT,
    tm_gm_dr_strt_fld_pos INT,
    tm_gm_dr_ply INT,
    tm_gm_dr_time TIME,
    tm_gm_dr_net_yds INT,
    tm_gm_dr_res ENUM('touchdown', 'field_goal', 'interception', 'fumble', 'punt', 'missed_field_goal', 'safety', 'downs', 'time', 'penalty', 'blocked_punt', 'blocked_field_goal'),
    tm_gm_dr_res_secondary ENUM('touchdown', 'field_goal', 'interception', 'fumble', 'punt', 'missed_field_goal', 'safety', 'downs', 'time', 'penalty', 'blocked_punt', 'blocked_field_goal'),
    FOREIGN KEY (team_id) REFERENCES nfl_team(team_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (game_id) REFERENCES nfl_game(game_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id),
    FOREIGN KEY (tm_gm_dr_qtr_id) REFERENCES nfl_gm_quarter(nfl_quarter_id),
    UNIQUE KEY uk_team_game_drive (team_id, game_id, tm_gm_dr_num)
);

CREATE TABLE tm_gm_exp_pts (
    tm_gm_exp_pts_id INT PRIMARY KEY AUTO_INCREMENT,
    team_id INT,
    week_id INT,
    game_id INT,
    season_id INT,
    tm_gm_exp FLOAT(7,4),
    tm_gm_off_exp FLOAT(7,4),
    tm_gm_pass_exp FLOAT(7,4),
    tm_gm_rush_exp FLOAT(7,4),
    tm_gm_tovr_exp FLOAT(7,4),
    tm_gm_def_exp FLOAT(7,4),
    tm_gm_def_pass_exp FLOAT(7,4),
    tm_gm_def_rush_exp FLOAT(7,4),
    tm_gm_def_tovr_exp FLOAT(7,4),
    tm_gm_st_exp FLOAT(7,4),
    tm_gm_st_ko_exp FLOAT(7,4),
    tm_gm_st_kr_exp FLOAT(7,4),
    tm_gm_st_p_exp FLOAT(7,4),
    tm_gm_st_pr_exp FLOAT(7,4),
    tm_gm_st_fgxp_exp FLOAT(7,4),
    FOREIGN KEY (team_id) REFERENCES nfl_team(team_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (game_id) REFERENCES nfl_game(game_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id),
    UNIQUE KEY uk_team_game (team_id, game_id)
);

CREATE TABLE tm_gm_stats (
    tm_gm_stats_id INT PRIMARY KEY AUTO_INCREMENT,
    team_id INT,
    week_id INT,
    game_id INT,
    season_id INT,
    tm_gm_first_dwn INT,
    tm_gm_rush_ply INT,
    tm_gm_rush_yds INT,
    tm_gm_rush_td INT,
    tm_gm_pass_cmp INT,
    tm_gm_pass_att INT,
    tm_gm_pass_yds INT,
    tm_gm_pass_td INT,
    tm_gm_pass_int INT,
    tm_gm_pass_sk INT,
    tm_gm_pass_sk_yds INT,
    tm_gm_net_pass_yds INT,
    tm_gm_tot_yds INT,
    tm_gm_fmb_tot INT,
    tm_gm_fmb_lost INT,
    tm_gm_to INT,
    tm_gm_pen INT,
    tm_gm_pen_yds_lost INT,
    tm_gm_third_dwn_conv INT,
    tm_gm_third_dwn_att INT,
    tm_gm_fourth_dwn_conv INT,
    tm_gm_fourth_dwn_att INT,
    tm_gm_top TIME,
    FOREIGN KEY (team_id) REFERENCES nfl_team(team_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (game_id) REFERENCES nfl_game(game_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id),
    UNIQUE KEY uk_team_game (team_id, game_id)
);

  CREATE TABLE tm_def_vs_qb (
      tm_def_vs_qb_id INT AUTO_INCREMENT PRIMARY KEY,
      team_id INT,
      season_id INT,
      week_id INT,
      tm_def_qb_two_pt_conv DECIMAL(7,4),
      tm_def_qb_rush_att INT,
      tm_def_qb_rush_yds INT,
      tm_def_qb_rush_td INT,
      UNIQUE KEY uk_tm_season (team_id, season_id, week_id),
      FOREIGN KEY (team_id) REFERENCES nfl_team(team_id),
      FOREIGN KEY (season_id) REFERENCES nfl_season(season_id),
      FOREIGN KEY (week_id) REFERENCES nfl_week(week_id)
  );

CREATE TABLE tm_def_vs_rb (
    tm_def_vs_rb_id INT AUTO_INCREMENT PRIMARY KEY,
    team_id INT,
    season_id INT,
    week_id INT,
    tm_def_rb_rush_att INT,
    tm_def_rb_rush_yds INT,
    tm_def_rb_rush_td INT,
    tm_def_rb_rec_tgt INT,
    tm_def_rb_rec INT,
    tm_def_rb_rec_yds INT,
    tm_def_rb_rec_td INT,
    UNIQUE KEY uk_tm_season (team_id, season_id, week_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (team_id) REFERENCES nfl_team(team_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id),
);

CREATE TABLE tm_def_vs_te (
    tm_def_vs_te_id INT AUTO_INCREMENT PRIMARY KEY,
    team_id INT,
    season_id INT,
    week_id INT,
    tm_def_te_tgt INT,
    tm_def_te_rec INT,
    tm_def_te_yds INT,
    tm_def_te_td INT,
    UNIQUE KEY uk_tm_season (team_id, season_id, week_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (team_id) REFERENCES nfl_team(team_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id),
);

CREATE TABLE tm_def_vs_wr (
    tm_def_vs_wr_id INT AUTO_INCREMENT PRIMARY KEY,
    team_id INT,
    season_id INT,
    week_id INT,
    tm_def_wr_tgt INT,
    tm_def_wr_rec INT,
    tm_def_wr_yds INT,
    tm_def_wr_td INT,
    UNIQUE KEY uk_tm_season (team_id, season_id, week_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (team_id) REFERENCES nfl_team(team_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id)
);

CREATE TABLE nfl_fastr_wr (
    nfl_fastr_wr_id INT AUTO_INCREMENT PRIMARY KEY,
    plyr_id INT,
    season_id INT,
    week_id INT,
    plyr_gm_rec_avg_cushion DECIMAL(7,4),
    plyr_gm_rec_avg_separation DECIMAL(7,4),
    plyr_gm_rec_avg_yac DECIMAL(7,4),
    plyr_gm_rec_avg_expected_yac DECIMAL(7,4),
    plyr_gm_rec_avg_yac_above_expectation DECIMAL(7,4),
    plyr_gm_rec_pct_share_of_intended_ay DECIMAL(7,4),
    plyr_gm_rec_tgt_share DECIMAL(7,4),
    plyr_gm_rec_epa DECIMAL(7,4),
    plyr_gm_rec_ay_share DECIMAL(7,4),
    plyr_gm_rec_wopr DECIMAL(7,4),
    plyr_gm_rec_racr DECIMAL(7,4),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_plyr_season (plyr_id, season_id, week_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id),
    FOREIGN KEY (plyr_id) REFERENCES plyr(plyr_id)
);

CREATE TABLE nfl_fastr_qb (
    nfl_fastr_qb_id INT AUTO_INCREMENT PRIMARY KEY,
    plyr_id INT,
    season_id INT,
    week_id INT,
    plyr_gm_pass_avg_ttt TIME,
    plyr_gm_pass_aggressiveness DECIMAL(7,4),
    plyr_gm_pass_avg_intended_ay DECIMAL(7,4),
    plyr_gm_pass_avg_ay_to_sticks DECIMAL(7,4),
    plyr_gm_pass_expected_cmp_pct DECIMAL(7,4),
    plyr_gm_pass_cmp_pct_above_expectation DECIMAL(7,4),
    plyr_gm_pass_epa DECIMAL(7,4),
    plyr_gm_pass_pacr DECIMAL(7,4),
    plyr_gm_pass_cpoe DECIMAL(7,4),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_plyr_season (plyr_id, season_id, week_id),
    FOREIGN KEY (week_id) REFERENCES nfl_week(week_id),
    FOREIGN KEY (season_id) REFERENCES nfl_season(season_id),
    FOREIGN KEY (plyr_id) REFERENCES plyr(plyr_id)
);