# Data Configuration

# Source data location
data:
  source: "${NFL_DATA_ROOT}/parquet_files/clean"  # Or relative: "../../parquet_files/clean"
  raw: "data/raw"  # Relative to project
  processed: "data/processed"

# Temporal scope
temporal:
  start_year: 2022
  end_year: 2025
  current_season: 2025
  historical_seasons: [2022, 2023, 2024]

# Data granularity
granularity:
  historical: "season_totals"  # 2022-2024: End-of-season only
  current: "weekly_cumulative"  # 2025: Weekly cumulative totals

# Table names organized by category
# Structure: directory/table_name/season=YYYY/week=W/data.parquet

tables:
  # Player game-level stats (directory: plyr_gm, partitioned by season/week)
  player_game_passing: "plyr_gm/plyr_gm_pass"
  player_game_rushing: "plyr_gm/plyr_gm_rush"
  player_game_receiving: "plyr_gm/plyr_gm_rec"
  player_game_defense: "plyr_gm/plyr_gm_def"
  player_game_fumbles: "plyr_gm/plyr_gm_fmbl"
  player_game_snap_counts: "plyr_gm/plyr_gm_snap_ct"
  player_game_starters: "plyr_gm/plyr_gm_starters"

  # Team game-level stats (directory: tm_gm, partitioned by season/week)
  team_game_stats: "tm_gm/tm_gm_stats"
  team_game_drive: "tm_gm/tm_gm_drive"
  team_game_expected_points: "tm_gm/tm_gm_exp_pts"

  # Game info (directory: gm_info, partitioned by season/week)
  game: "gm_info/nfl_game"
  game_info: "gm_info/nfl_game_info"
  game_weather: "gm_info/nfl_gm_weather"
  game_play_by_play: "gm_info/nfl_gm_pbp"
  injury_report: "gm_info/injury_report"

  # Player season cumulative stats (directory: plyr_szn, partitioned by season/week)
  player_season_passing: "plyr_szn/plyr_pass"
  player_season_rushing: "plyr_szn/plyr_rush"
  player_season_receiving: "plyr_szn/plyr_rec"
  player_season_defense: "plyr_szn/plyr_def"
  player_season_redzone_passing: "plyr_szn/plyr_rz_pass"
  player_season_redzone_rushing: "plyr_szn/plyr_rz_rush"
  player_season_redzone_receiving: "plyr_szn/plyr_rz_rec"
  player_season_scoring: "plyr_szn/plyr_scoring"

  # Team season cumulative stats (directory: tm_szn, partitioned by season/week)
  team_season_passing: "tm_szn/tm_pass"
  team_season_rushing: "tm_szn/tm_rush"
  team_season_receiving: "tm_szn/tm_rec"
  team_season_defense: "tm_szn/tm_def"
  team_season_defense_passing: "tm_szn/tm_def_pass"
  team_season_defense_rushing: "tm_szn/tm_def_rush"
  team_season_conversions: "tm_szn/tm_conv"
  team_season_defense_conversions: "tm_szn/tm_def_conv"
  team_season_defense_drive_against_avg: "tm_szn/tm_def_dr_against_avg"
  team_season_defense_vs_qb: "tm_szn/tm_def_vs_qb"
  team_season_defense_vs_rb: "tm_szn/tm_def_vs_rb"
  team_season_defense_vs_te: "tm_szn/tm_def_vs_te"
  team_season_defense_vs_wr: "tm_szn/tm_def_vs_wr"
  standings: "tm_szn/nfl_standings"

  # Reference data (directory: players, partitioned by season)
  players: "players/plyr"
  multi_team_players: "players/multi_tm_plyr"

  # Static data (no partitioning or partitioned by season only)
  teams: "nfl_team.parquet"
  seasons: "nfl_season.parquet"
  weeks: "static/nfl_week"
  game_quarters: "nfl_gm_quarter.parquet"

# Target variable
target:
  name: "plyr_gm_rec_yds"
  table: "plyr_gm_rec"
  description: "Player game receiving yards"

# Data processing
processing:
  handle_nulls: true
  remove_duplicates: true
  validate_schema: true
  min_games_threshold: 3  # Minimum games for player inclusion
