# Model Configuration

# Model type
model:
  type: "RandomForestRegressor"
  framework: "sklearn"

# Hyperparameters (baseline)
hyperparameters:
  n_estimators: 100
  max_depth: null  # No limit (default)
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: "sqrt"  # sqrt of total features
  bootstrap: true
  random_state: 42
  n_jobs: -1  # Use all CPU cores
  verbose: 0

# Training configuration
training:
  test_size: 0.2
  validation_size: 0.2  # From training set
  random_state: 42

  # Temporal split (recommended for time series)
  use_temporal_split: true
  train_years: [2022, 2023, 2024]
  test_year: 2025
  test_weeks: [1, 2, 3, 4, 5]  # Test on first 5 weeks of 2025

  # Cross-validation
  cross_validation:
    enabled: false  # Enable for hyperparameter tuning
    n_folds: 5
    strategy: "time_series"  # or "k_fold"

# Hyperparameter tuning (optional)
tuning:
  enabled: false
  method: "grid_search"  # or "random_search", "bayesian"

  param_grid:
    n_estimators: [50, 100, 200]
    max_depth: [10, 20, 30, null]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2, 4]
    max_features: ["sqrt", "log2"]

  scoring: "neg_mean_squared_error"
  cv_folds: 5

# Feature importance
feature_importance:
  compute: true
  plot: true
  save_path: "evaluation/visualizations/feature_importance"

# Model saving
saving:
  save_path: "models/saved/production"
  model_name: "rf_model_v1"
  save_format: "pkl"  # or "joblib"
  include_metadata: true

  metadata:
    version: "v1"
    description: "Baseline Random Forest model"
    features_version: "v1_baseline"
    trained_date: null  # Auto-populated
    performance_metrics: null  # Auto-populated

# Reproducibility
reproducibility:
  random_seed: 42
  deterministic: true
