# Centralized Path Configuration

# Project root
project_root: "C:/Users/nocap/Desktop/code/NFL_ml/models/rf_rec_yds"

# Data paths
data:
  source: "C:/Users/nocap/Desktop/code/NFL_ml/parquet_files/clean"
  raw: "data/raw"
  processed: "data/processed"
  processed_game: "data/processed/game_features"
  processed_player: "data/processed/player_features"
  processed_team: "data/processed/team_features"
  feature_sets: "data/feature_sets"
  feature_sets_v1: "data/feature_sets/v1_baseline"
  feature_sets_v2: "data/feature_sets/v2_enhanced"
  splits: "data/splits"
  splits_cv: "data/splits/cross_validation"
  splits_temporal: "data/splits/temporal"

# Feature paths
features:
  builders: "features/builders"
  engineering: "features/engineering"
  selection: "features/selection"
  pipelines: "features/pipelines"

# Model paths
models:
  configs: "models/configs"
  training: "models/training"
  pipelines: "models/pipelines"
  saved: "models/saved"
  production: "models/saved/production"
  checkpoints: "models/saved/checkpoints"
  inference: "models/inference"

# Evaluation paths
evaluation:
  metrics: "evaluation/metrics"
  validation: "evaluation/validation"
  testing: "evaluation/testing"
  reports: "evaluation/reports"
  visualizations: "evaluation/visualizations"
  viz_feature_importance: "evaluation/visualizations/feature_importance"
  viz_predictions: "evaluation/visualizations/prediction_distribution"
  viz_residuals: "evaluation/visualizations/residual_plots"

# Experiment paths
experiments:
  tracking: "experiments/tracking"
  mlruns: "experiments/tracking/mlruns"
  configs: "experiments/configs"
  results: "experiments/results"

# Output paths
outputs:
  predictions: "outputs/predictions"
  reports: "outputs/reports"
  visualizations: "outputs/visualizations"

# Documentation and support paths
docs: "docs"
prompts: "prompts"
notebooks: "notebooks"
notebooks_feature_analysis: "notebooks/feature_analysis"
notebooks_model_dev: "notebooks/model_development"
notebooks_results: "notebooks/results_analysis"

# Utility paths
utils: "utils"
tests: "tests"
scripts: "scripts"

# Logging
logs: "logs"
